# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        "/:title/"

# Setup
title:            'Frederick Jansen'
tagline:          'Things might get technical'
description:      'Full-time developer, occasional designer.'
meta:             'Full-time developer, occasional designer. Passionate about making things work.'
url:              http://prettyplease.me

author:
  name:           'Frederick Jansen'
  url:            http://prettyplease.me

paginate:         5

# Custom vars
#version:          2.0.0

github:
  repo:           https://github.com/frederickjansen

linkedin:         http://be.linkedin.com/in/jansenfrederick
